services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    command: sh -c "npx wait-port mysql:3306 && npm run dev"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: sh -c "npx wait-port backend:3000 && npm run dev -- --host"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
